---
title: "An Introduction to R"
author:
  - "Reio Tanji"
  - "Osaka Univ., Graduate School of Econ."
date: "April, 2022"
output: 
  revealjs::revealjs_presentation:
    self_contained: FALSE
    theme: serif
    css: introduction.css
    reveal_plugins: ["menu"]
    reveal_options:
      menu:
        numbers: TRUE
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# R言語を使う

**R言語とは？**

-   "*R is a free software environment for statistical computing and graphics*" (from [The R Project for Statistical Computing](https://www.r-project.org/))

    -   統計計算、グラフ作成を行うことができる無料のツール
    -   データの収集、管理、分析から結果の出力・プレゼンテーションの作成までを一つの言語で行うことも出来る
    -   この資料もRを使って作成(R Markdown)

-   目標

    -   今回は、Rの基本的な操作方法を学習した上で、論文執筆の上で最低限必要なアウトプットのための技術習得をめざす

## Rでできること

-   データの操作：`tidyverse`

    -   データの取得：デフォルトのデータセット、csvファイル等の読み込み
    -   データの整理：必要な情報の抽出、データの変形、新たな変数の作成と保存

-   データの可視化

    -   変数間の関係を視覚的に描写：`graphics`, `ggplot2`

-   データ分析

    -   基本統計量の作成
    -   計量経済学・統計学で用いられる様々な手法の実装
    -   結果の出力

-   レポートの作成

    -   分析結果をスライドにして報告 `RMarkdown`

        -   Word, Powerpoint形式でファイルを出力

    -   出力の保存や体裁を整える手間が削減できる

## 基本構造

-   基本的には、というか全ての命令は

    -   Rに命令を投げる→命令に従って計算(描画・読み込みなど)を行う

    -   必要であればアウトプットを返す

    の繰り返し

```{=html}
<!-- -->
```
-   エレベーターの3階ボタンを押す→3階に向かう、ドアを開ける

    -   ボタンを押すエネルギーでエレベータが動いているわけではない
    -   ワイヤーをどれだけ巻き取ればどれだけ上昇・下降するのか、ドアを開けるためにどの部分にどれだけ力を加えればいいのか、が3回ボタンを押したときに発せられる命令として書かれている

-   この命令を一つ一つ書く作業を行う

# Setup

-   インストール

    -   **R言語**と**R Studio**の2つをインストール

        -   R言語をスムーズに利用するためのツール：開発環境がRStudio

-   

# 基本操作

# データの操作

# データの可視化

# 分析と結果の表示

# RMarkdownを用いたレポートの作成
